services:
  ai-gmail-kanban-fe:
    image: thuanpham777/ai-gmail-kanban-fe:latest
    container_name: ai-gmail-kanban-fe
    ports:
      - "5173:80"
    restart: always
    labels:
      - "traefik.http.routers.ai-gmail-kanban-fe-secure.rule=Host(`ai-gmail-kanban.lptdevops.website`)"
      - "traefik.http.routers.ai-gmail-kanban-fe-secure.entrypoints=websecure"
      - "traefik.http.routers.ai-gmail-kanban-fe-secure.tls=true"
      - "traefik.http.routers.ai-gmail-kanban-fe-secure.tls.certresolver=leresolver"

      - "traefik.http.routers.ai-gmail-kanban-fe.rule=Host(`ai-gmail-kanban.lptdevops.website`)"
      - "traefik.http.routers.ai-gmail-kanban-fe.entrypoints=web"
      - "traefik.http.routers.ai-gmail-kanban-fe.middlewares=redirect-to-https"
      - "traefik.http.services.ai-gmail-kanban-fe.loadbalancer.server.port=80"
    networks:
      - PrviNetwork

networks:
  PrviNetwork:
    external: true